version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: beniexbio_app_backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://beniex_bio_db:27017/beniex_db
      - PORT=3000
    depends_on:
      - mongo
    networks: 
      - beniexbio_network  

  mongo:
    image: mongo:8
    container_name: beniex_bio_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: beniex_bio
      MONGO_INITDB_ROOT_PASSWORD: "#@bio_db$2025@#"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: 
      - beniexbio_network    

volumes:
  mongo_data:
    name: beniexbio_mongo_data 
    driver: local

networks:
  beniexbio_network:
    driver: bridge
